"""
Generate data for the GPS burst labeling and visualization app.

Steps:
- Matching GPS and IMU data either from the database or from a calibrated CSV file
- Performing inference on IMU data to get behavior labels
- Combine them

Data format:
```
device_id, date_time,index,groun_truth label,imu_x,imu_y,imu_z,gps_m/s,label,confidence,latitude,longitude,altitude(optional)
298,2010-06-07 09:43:05,0,-1,-0.167287,-0.004737,1.014680,0.200996,5,0.986863,53.009282,4.717725
```

Notes:
- In Ornitela devices x and y switched
- In scripts/data/merge_simon_data.py: provides the similar format but given calibration file,
separate behavior labels that is generated by scripts/classify_birds.py. This script can be accessed by Google Colab.
Since format is specific, the other script is made.
"""

import os
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from omegaconf import OmegaConf
from sklearn.metrics import confusion_matrix
from torch.utils.data import DataLoader

from behavior import data as bd
from behavior import map as bmap
from behavior import model as bm
from behavior import model_utils as bmu
from behavior import utils as bu

seed = 32984
bu.set_seed(seed)


def test_confmat():
    # fmt: off
    expected = np.array([
       [ 638,    1,    0,    0,    0,    0,    0,    4,    0],
       [   1,   36,    0,    0,    0,    0,    0,    1,    0],
       [   0,    0,  515,    4,   11,    0,    0,    7,    0],
       [   0,    0,   11,  157,    1,    0,    2,    0,    5],
       [   0,    0,   10,    0,  719,    0,    0,    0,    0],
       [   0,    0,    7,    0,    2, 1475,    9,    0,    9],
       [   0,    0,    2,    0,    0,    5,  327,    0,    3],
       [   2,    1,   26,    0,    0,    0,    0,  121,    1],
       [   0,    0,    4,    1,    0,   14,   26,    0,  180]])
    # fmt: on
    seed = 32984
    glen = 20
    exp = 125
    labels_to_use = [0, 1, 2, 3, 4, 5, 6, 8, 9]
    in_channel, width, n_classes = 4, 30, len(labels_to_use)
    data_file = Path("/home/fatemeh/Downloads/bird/data/final/starts.csv")
    checkpoint_file = Path(f"/home/fatemeh/Downloads/bird/results/{exp}_best.pth")

    bu.set_seed(seed)
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    model = bm.BirdModel(in_channel, width, n_classes).to(device)
    bm.load_model(checkpoint_file, model, device)
    model.eval()

    df = pd.read_csv(data_file, header=None)
    df = df[df[3].isin(labels_to_use)].reset_index(drop=True)
    df[3] = df[3].map({lab: i for i, lab in enumerate(labels_to_use)})
    igs = df[[4, 5, 6, 7]].values.reshape(-1, glen, 4)
    labels = df.iloc[::glen, 3].values

    dataset = bd.BirdDataset(igs)
    loader = DataLoader(
        dataset,
        batch_size=len(dataset),
        shuffle=False,
        num_workers=1,
        drop_last=False,
    )
    data = next(iter(loader))

    probs, preds = bu.inference(data, model, device)
    label_names = [bu.ind2name[i] for i in labels_to_use]
    confmat = confusion_matrix(labels, preds, labels=np.arange(len(label_names)))
    assert np.testing.assert_equal(confmat, expected)


# test_confmat()


def fetch_gps_data(database_url, device_id, start_time, end_time):
    """
    Fetch GPS data from the database.
    `device_info_serial, date_time, latitude, longitude, altitude
    """

    sql_query = f"""
    SELECT *
    FROM gps.ee_tracking_speed_limited
    WHERE device_info_serial = {device_id} AND date_time BETWEEN '{start_time}' AND '{end_time}'
    ORDER BY date_time
    """
    results = bd.query_database_improved(database_url, sql_query)
    if len(results) == 0:
        raise ValueError("No GPS data found")

    return [
        [
            result[0],  # device_info_serial
            str(result[1]),  # date_time
            result[2],  # latitude
            result[3],  # longitude
            result[4],  # altitude
        ]
        for result in results
        if result[-4] is not None  # speed_2d
    ]


def fetch_merge_gps(df, database_url):
    """
    Fetch GPS data and merge with IMU data
    """

    groups = df.groupby([0])
    gps_data = []
    for k, group in groups:
        start_time = group.iloc[0, 1]
        end_time = group.iloc[-1, 1]
        device_id = group.iloc[0, 0]
        per_group = fetch_gps_data(database_url, device_id, start_time, end_time)
        gps_data.extend(per_group)
    gps_data = pd.DataFrame(gps_data, columns=[0, 1, 10, 11, 12])

    df = df.merge(gps_data, on=[0, 1], how="inner")

    return df


def load_database_app_data(data_file, cfg):
    df = pd.read_csv(data_file, header=None)
    df = df.sort_values([0, 1, 2])
    # GPS 2D speed smaller than 30 m/s
    df = df[df[7] < 30.0].copy()
    # Clip IMU x, y, z values between -2, 2
    df[[4, 5, 6]] = df[[4, 5, 6]].clip(-2.0, 2.0)
    df = df.iloc[:, :8].copy()
    df[8] = -1
    df[9] = -1
    df = fetch_merge_gps(df, cfg.database_url)
    return df[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]


def infer_save_app_data(df, save_file, cfg):
    df = df.sort_values([0, 1, 2])
    # GPS 2D speed smaller than 30 m/s
    df = df[df[7] < 30.0].copy()
    # Clip IMU x, y, z values between -2, 2
    df[[4, 5, 6]] = df[[4, 5, 6]].clip(-2.0, 2.0)
    df = bmu.infer_update_classes(
        df,
        cfg.glen,
        cfg.labels_to_use,
        cfg.checkpoint_file,
        cfg.n_classes,
        cfg.model_name,
        cfg.model_parameters,
    )
    df.to_csv(save_file, index=False, header=None, float_format="%.6f")


def prepare_app_class_data(data_file, save_file, cfg):
    df = pd.read_csv(data_file, header=None)
    infer_save_app_data(df, save_file, cfg)


def prepare_database_app_class_data(data_file, save_file, cfg):
    df = load_database_app_data(data_file, cfg)
    infer_save_app_data(df, save_file, cfg)


def prepare_calibrated_app_data(data_file: Path, save_file: Path) -> None:
    """
    Reads calibrated GPS/SENSOR CSV data and converts it to the app input format.
    It keeps GPS records only when latitude and longitude are valid and
    the next row is a SENSOR record from the same device
    with an absolute timestamp difference of at most 2 seconds.
    The valid GPS values are forward-filled to the following SENSOR rows from the same device.
    SENSOR rows after invalid GPS records are discarded.
    Finally, SENSOR rows are grouped by device_id and UTC_datetime,
    trimmed so each group size is divisible by 20, indexed from zero, and saved to a headerless CSV file.

    The input file:
      is a CSV file containing calibrated GPS and SENSOR records.
      Each row belongs to one device and has a UTC timestamp in the column UTC_datetime.
      GPS rows are identified by datatype == "GPS" and contain location fields
      such as Latitude, Longitude, Altitude_m, and speed_km_h.
      SENSOR rows are identified by datatype == "SENSORS" and
      contain IMU acceleration fields x_g, y_g, and z_g. GPS rows
      with both Latitude and Longitude equal to zero are treated as invalid and are not used.

    The output file is a CSV file without a header.
    It contains only SENSOR rows that can be matched to a valid nearby GPS row. The output columns are:

    device_id, UTC_datetime, index, -1, x_g, y_g, z_g, speed_m_s, -1, -1, Latitude, Longitude, Altitude_m

    The speed value is converted from km/h to m/s.
    The index starts at 0 for each device_id and UTC_datetime group and increases within that group.
    Only groups with a number of SENSOR rows divisible by 20 are saved;
    extra rows at the end of a group are removed.
    """
    cols = [
        "device_id",
        "UTC_datetime",
        "datatype",
        "Latitude",
        "Longitude",
        "Altitude_m",
        "speed_km_h",
        "x_g",
        "y_g",
        "z_g",
    ]

    df = pd.read_csv(data_file, usecols=cols)
    df["UTC_datetime"] = pd.to_datetime(df["UTC_datetime"])

    is_gps = df["datatype"].eq("GPS")
    is_sensor = df["datatype"].eq("SENSORS")

    gps_next_sensor = (
        is_gps
        & df["datatype"].shift(-1).eq("SENSORS")
        & df["device_id"].eq(df["device_id"].shift(-1))
        & ~(df["Latitude"].eq(0) & df["Longitude"].eq(0))
    )

    time_diff = df["UTC_datetime"].shift(-1) - df["UTC_datetime"]

    valid_gps = gps_next_sensor & (time_diff.abs() <= pd.Timedelta(seconds=2))

    # The latest GPS row before each SENSOR row.
    df["gps_datetime"] = df["UTC_datetime"].where(is_gps)
    df["gps_datetime"] = df.groupby("device_id")["gps_datetime"].ffill()

    # The latest valid GPS row before each SENSOR row.
    df["valid_gps_datetime"] = df["UTC_datetime"].where(valid_gps)
    df["valid_gps_datetime"] = df.groupby("device_id")["valid_gps_datetime"].ffill()

    # Keep GPS values only from valid GPS rows, then forward-fill them.
    gps_cols = ["Latitude", "Longitude", "Altitude_m", "speed_km_h"]

    for col in gps_cols:
        df[col] = df[col].where(valid_gps)
        df[col] = df.groupby("device_id")[col].ffill()

    # Keep SENSOR rows only when the most recent GPS is valid.
    df_app = df[
        is_sensor
        & df["gps_datetime"].eq(df["valid_gps_datetime"])
        & df["Latitude"].notna()
        & df["Longitude"].notna()
    ].copy()

    # Keep only rows up to a count divisible by 20 per device_id and SENSOR datetime.
    df_app["index"] = df_app.groupby(["device_id", "UTC_datetime"]).cumcount()

    n_per_group = df_app.groupby(["device_id", "UTC_datetime"])["index"].transform(
        "size"
    )
    keep_n = n_per_group - (n_per_group % 20)

    df_app = df_app[df_app["index"] < keep_n].copy()

    # Recreate index after filtering.
    df_app["index"] = df_app.groupby(["device_id", "UTC_datetime"]).cumcount()

    out = pd.DataFrame(
        {
            0: df_app["device_id"],
            1: df_app["UTC_datetime"].dt.strftime("%Y-%m-%d %H:%M:%S"),
            2: df_app["index"],
            3: -1,
            4: df_app["y_g"],  # In Ornitela devices x and y switched
            5: df_app["x_g"],
            6: df_app["z_g"],
            7: df_app["speed_km_h"] / 3.6,  # speed m/s
            8: -1,
            9: -1,
            10: df_app["Latitude"],
            11: df_app["Longitude"],
            12: df_app["Altitude_m"],
        }
    )

    out.to_csv(save_file, index=False, header=False, float_format="%.6f")


def check_consecutive_gps_sensor_time_diff(data_file):
    """
    Check the time difference between consecutive GPS and SENSORS rows for the same device_id.
    """
    cols = [
        "device_id",
        "UTC_datetime",
        "datatype",
        "Latitude",
        "Longitude",
        "Altitude_m",
        "speed_km_h",
        "x_g",
        "y_g",
        "z_g",
    ]

    df = pd.read_csv(data_file, usecols=cols)
    df["UTC_datetime"] = pd.to_datetime(df["UTC_datetime"])

    gps_next_sensor = (
        df["datatype"].eq("GPS")
        & df["datatype"].shift(-1).eq("SENSORS")
        & df["device_id"].eq(df["device_id"].shift(-1))
        & ~(df["Latitude"].eq(0) & df["Longitude"].eq(0))
    )

    time_diff = (
        df["UTC_datetime"].shift(-1)[gps_next_sensor]
        - df["UTC_datetime"][gps_next_sensor]
    )

    print(time_diff.value_counts().sort_index())
    print("max:", time_diff.max())

    print(
        df.loc[
            gps_next_sensor,
            ["device_id", "UTC_datetime", "Latitude", "Longitude", "Altitude_m"],
        ]
        .assign(
            gps_time=df["UTC_datetime"][gps_next_sensor],
            next_sensor_time=df["UTC_datetime"].shift(-1)[gps_next_sensor],
            time_diff=time_diff,
        )
        .sort_values("time_diff", ascending=False)
        .head(20)
    )

    print("done")


def plot_labeled_data(df, ind2name, glen=20):

    y_limits = [-3.5, 3.5]

    # Data
    df = df.sort_values([0, 1, 2]).reset_index(drop=True)
    assert len(np.unique(df[0])) == 1
    assert len(np.unique(df[1])) == 1
    assert len(np.unique(df[7])) == 1
    data = df[[4, 5, 6]].values  # IMU data
    indices = df[2].values  # Indices

    # Draw IMU data
    width = 4 * len(df) // glen + 2
    fig, ax = plt.subplots(1, 1, figsize=(width, 4.3))
    mgr = plt.get_current_fig_manager()
    # # x=100, y=100 on screen
    mgr.window.wm_geometry("+100+100")  # TkAgg
    # mgr.window.setGeometry(100, 100, width_px, height_px) # Qt5Agg
    ax.plot(
        indices,
        data[:, 0],
        "r-*",
        indices,
        data[:, 1],
        "b-*",
        indices,
        data[:, 2],
        "g-*",
    )

    # Set axis limits
    ax.set_xlim(indices[0], indices[-1] + 1)
    ax.set_ylim(*y_limits)
    ax.set_yticks([y_limits[0], 0, y_limits[1]])
    ax.set_xticks(range(indices[0], indices[-1] + glen, glen))

    # Draw horizontal zero line
    ax.plot([indices[0], indices[-1]], [0, 0], "-", color="black")

    # Draw vertical lines
    for i in range(0, len(df), glen):
        s_ind = df.iloc[i, 2]
        e_ind = s_ind + glen
        label_id = df.iloc[i, 3]
        pred_id = df.iloc[i, 8]
        prob = df.iloc[i, 9]
        label = ind2name[label_id] if label_id != -1 else None
        pred = ind2name[pred_id]
        text_loc = [s_ind + (e_ind - s_ind + 1) // 4, y_limits[1] - 0.5]
        text = f"{label}, {pred}, {prob:.3f}"
        ax.text(*text_loc, text, color="black", fontsize=9)
        ax.plot([s_ind, s_ind], y_limits, "-", color="black")
    ax.plot([e_ind, e_ind], y_limits, "-", color="black")

    text = f"{df.iloc[0,0]}, {df.iloc[0,1]},gps:{df.iloc[0,7]:.2f}"
    plt.title(f"{text}", fontsize=10)  # GPS info
    fig.tight_layout()
    # # ig.subplotpars.left, fig.subplotpars.right, fig.subplotpars.bottom, fig.subplotpars.top
    # fig.subplots_adjust(left=.038,right=.97,bottom=.09,top=.95)
    return fig


if __name__ == "__main__":
    # Prepare data
    cfg = dict(
        glen=20,
        exp=197,
        labels_to_use=[0, 1, 2, 3, 4, 5, 6, 8, 9],
        in_channe=4,
        width=30,
        n_classes=None,
        checkpoint_file=Path(f"/home/fatemeh/Downloads/bird/results"),
        database_url=None,
        model_name="BirdModelSmallDilated",
        # in_channels=7 for exp197, which takes the magnitude channels;
        # 4 for exp194/195/196. Nothing else changes.
        model_parameters=dict(
            in_channels=7,
            mid_channels=20,
            out_channels=None,
            dropout=0.15,
        ),
    )

    cfg = OmegaConf.create(cfg)
    cfg.n_classes = len(cfg.labels_to_use)
    cfg.model_parameters.out_channels = cfg.n_classes
    cfg.checkpoint_file = cfg.checkpoint_file / f"{cfg.exp}_best.pth"
    cfg.database_url = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASS')}@pub.e-ecology.nl:5432/eecology"

    # Edit these two paths to change the run. One output file per model, named
    # after the experiment, so earlier ones are kept.
    app_file = Path(
        "/home/fatemeh/Downloads/bird/data/simon/rose_gimu_behavior_1223941_1620120.csv"
    )
    save_file = app_file.with_name(f"{app_file.stem}_{cfg.exp}.csv")
    prepare_app_class_data(app_file, save_file, cfg)


"""
# On unlabeled data
data_path = Path("/home/fatemeh/Downloads/bird/data/ssl/final/gull")
save_path = Path("/home/fatemeh/Downloads/bird/data/ssl/gimu_behavior/gull")
save_path.mkdir(parents=True, exist_ok=True)
data_paths = sorted(list(data_path.glob("*")), key=lambda x: int(x.stem))
for data_file in data_paths:
    device_id = int(data_file.stem)
    save_file = save_path / f"{device_id}.csv"
    prepare_database_app_class_data(data_file, save_file, cfg)

# On the ground truth data
data_file = Path("/home/fatemeh/Downloads/bird/data/final/starts.csv")
save_file = Path(
    "/home/fatemeh/Downloads/bird/data/final/starts_gimu_behavior.csv"
)
prepare_database_app_class_data(data_file, save_file, cfg)

# On Rose data
data_file = Path("/home/fatemeh/Downloads/bird/data/simon/all_devices_calibrated.csv")
app_file = Path("/home/fatemeh/Downloads/bird/data/simon/rose_data.csv")
save_file = Path("/home/fatemeh/Downloads/bird/data/simon/rose_gimu_behavior.csv")
# check_consecutive_gps_sensor_time_diff(data_file)
# prepare_calibrated_app_data(data_file, app_file)
prepare_app_class_data(app_file, save_file, cfg)

# On App data without classification
app_file = Path("/home/fatemeh/Downloads/bird/data/ssl/gimu_behavior/gull/6004.csv")
save_file = Path(
    "/home/fatemeh/Downloads/bird/data/ssl/gimu_behavior/gull/6004_194.csv"
)
prepare_app_class_data(app_file, save_file, cfg)
"""


"""
# Visualize IMU and behavior
# gimu_beh_file = Path("/home/fatemeh/Downloads/bird/data/ssl/gimu_behavior/gull/298.csv")
# dt = (298, "2010-06-07 09:43:05")
gimu_beh_file = Path("/home/fatemeh/Downloads/bird/data/final/starts_gimu_behavior.csv")
dt = (806, "2014-05-16 12:56:53")
dt = (6210, "2016-05-09 10:26:25")
df = pd.read_csv(gimu_beh_file, header=None)


groups = df.groupby(by=[0, 1])
dts = list(groups.groups.keys())
# for _ in range(5):
# i = np.random.randint(0, len(dts))
# print(i)
for i in [1536, 179]:
    dt = dts[i]
    dataframe = groups.get_group(dt)
    fig = plot_labeled_data(dataframe, bu.ind2name)

    # Visualize map
    lat, lon = dataframe.iloc[0, [10, 11]]  # 52.00947, 4.34438
    map_image = bmap.get_centered_map_image(lat, lon, zoom=15)
    map_image.show()

print("done")
"""
