# None: means leave it empty
# query database
start_time: "2012-05-17 00:00:59" # Value str. It should be "year-month-day hour:minute:second"
end_time: "2012-05-17 00:00:59" # Value str. It should be "year-month-day hour:minute:second"
device_id: 541 # Value int. 
database_url: "postgresql://{username}:{password}@{host}:{port}/{database_name}" # Value: str. 

model_checkpoint: /content/45_best.pth # Value: Path
save_path: /content/result # Value: Path
# model_checkpoint: /home/fatemeh/Downloads/bird/result/45_best.pth # Value: Path
# save_path: /home/fatemeh/Downloads/bird/result/failed/exp1 # Value: Path